local set = vim.opt

set.swapfile = false
set.helplang = "ja"
set.syntax = "on"
set.encoding = "utf-8"
set.title = true
set.number = true
set.ruler = true
set.smartcase = true
set.cursorline = true
set.shiftwidth = 4
set.tabstop = 4
set.hls = true
set.clipboard = "unnamed"
set.showmatch = true
set.fileencodings = "utf-8"
set.updatetime = 300
set.laststatus = 2
set.expandtab = true
set.autoindent = true
set.smartindent = true
